apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubernetes-monitor
  name: k8s-monitor
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kubernetes-monitor
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      creationTimestamp: null
      labels:
        app: kubernetes-monitor
    spec:
      containers:
        - name: test
          image: nginx:latest
