apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubernetes-monitor
  name: k8s-monitor
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: kubernetes-monitor
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
