apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubernetes-monitor
  name: kubernetes-monitor
  namespace: default
spec:
  ports:
    - name: http
      port: 9016
      protocol: TCP
      targetPort: 9016
  selector:
    app: kubernetes-monitor
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
